/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Academic Calendar
 * API para o Academic Calendar
 * OpenAPI spec version: 0.0.1
 */
export type PostSignupBody = {
  /** @minLength 2 */
  name: string
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string
  /** @minLength 6 */
  password: string
}

export type PostSignup201Message = string | null

export type PostSignup201 = {
  token: string
  message: PostSignup201Message
}

export type PostSignup400Token = string | null

export type PostSignup400 = {
  token: PostSignup400Token
  message: string
}

export type PostSignup404Token = string | null

export type PostSignup404 = {
  token: PostSignup404Token
  message: string
}

export type PostSigninBody = {
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string
  /** @minLength 6 */
  password: string
}

export type PostSignin200Message = string | null

export type PostSignin200 = {
  token: string
  message: PostSignin200Message
}

export type PostSignin400Token = string | null

export type PostSignin400 = {
  token: PostSignin400Token
  message: string
}

export type PostSignin404Token = string | null

export type PostSignin404 = {
  token: PostSignin404Token
  message: string
}

export type PostCoursesBody = {
  /** @minLength 2 */
  description: string
  /** @minLength 6 */
  title: string
}

export type PostCourses201CourseCreatedAt = string | null

export type PostCourses201CourseUpdatedAt = string | null

export type PostCourses201Course = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$ */
  id: string
  title: string
  description: string
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$ */
  userId: string
  createdAt: PostCourses201CourseCreatedAt
  updatedAt: PostCourses201CourseUpdatedAt
}

export type PostCourses201 = {
  course: PostCourses201Course
}

export type PostCourses400 = {
  message: string
}

export type PostCourses404 = {
  message: string
}

export type GetCourses200CoursesItemCreatedAt = string | null

export type GetCourses200CoursesItemUpdatedAt = string | null

export type GetCourses200CoursesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$ */
  id: string
  title: string
  description: string
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$ */
  userId: string
  createdAt: GetCourses200CoursesItemCreatedAt
  updatedAt: GetCourses200CoursesItemUpdatedAt
}

export type GetCourses200 = {
  courses: GetCourses200CoursesItem[]
}

export type GetCourses401 = {
  message: string
}

export type PostSemestersBodySemester =
  (typeof PostSemestersBodySemester)[keyof typeof PostSemestersBodySemester]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostSemestersBodySemester = {
  first: 'first',
  second: 'second',
} as const

export type PostSemestersBody = {
  semester: PostSemestersBodySemester
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$ */
  courseId: string
}

export type PostSemesters201SemesterSemester =
  (typeof PostSemesters201SemesterSemester)[keyof typeof PostSemesters201SemesterSemester]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostSemesters201SemesterSemester = {
  first: 'first',
  second: 'second',
} as const

export type PostSemesters201SemesterCreatedAt = string | null

export type PostSemesters201SemesterUpdatedAt = string | null

export type PostSemesters201Semester = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$ */
  id: string
  semester: PostSemesters201SemesterSemester
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$ */
  courseId: string
  createdAt: PostSemesters201SemesterCreatedAt
  updatedAt: PostSemesters201SemesterUpdatedAt
}

export type PostSemesters201 = {
  semester: PostSemesters201Semester
}

export type PostSemesters400 = {
  message: string
}

export type PostSemesters404 = {
  message: string
}

export type PostDisciplinesBody = {
  /** @minLength 2 */
  title: string
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$ */
  semesterId: string
}

export type PostDisciplines201DisciplineCreatedAt = string | null

export type PostDisciplines201DisciplineUpdatedAt = string | null

export type PostDisciplines201Discipline = {
  id: string
  title: string
  createdAt: PostDisciplines201DisciplineCreatedAt
  updatedAt: PostDisciplines201DisciplineUpdatedAt
  semesterId: string
}

export type PostDisciplines201 = {
  discipline: PostDisciplines201Discipline
}

export type PostDisciplines400 = {
  message: string
}

export type PostDisciplines404 = {
  message: string
}

export type GetCoursesCourseIdSemesters200SemestersItemSemester =
  (typeof GetCoursesCourseIdSemesters200SemestersItemSemester)[keyof typeof GetCoursesCourseIdSemesters200SemestersItemSemester]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetCoursesCourseIdSemesters200SemestersItemSemester = {
  first: 'first',
  second: 'second',
} as const

export type GetCoursesCourseIdSemesters200SemestersItemCreatedAt = string | null

export type GetCoursesCourseIdSemesters200SemestersItemUpdatedAt = string | null

export type GetCoursesCourseIdSemesters200SemestersItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$ */
  id: string
  semester: GetCoursesCourseIdSemesters200SemestersItemSemester
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$ */
  courseId: string
  createdAt: GetCoursesCourseIdSemesters200SemestersItemCreatedAt
  updatedAt: GetCoursesCourseIdSemesters200SemestersItemUpdatedAt
}

export type GetCoursesCourseIdSemesters200 = {
  semesters: GetCoursesCourseIdSemesters200SemestersItem[]
}

export type GetCoursesCourseIdSemesters401 = {
  message: string
}

export type GetCoursesCourseIdSemesters404 = {
  message: string
}

export type GetSemestersSemesterIdDisciplines200DisciplinesItemCreatedAt =
  | string
  | null

export type GetSemestersSemesterIdDisciplines200DisciplinesItemUpdatedAt =
  | string
  | null

export type GetSemestersSemesterIdDisciplines200DisciplinesItem = {
  id: string
  title: string
  createdAt: GetSemestersSemesterIdDisciplines200DisciplinesItemCreatedAt
  updatedAt: GetSemestersSemesterIdDisciplines200DisciplinesItemUpdatedAt
  semesterId: string
}

export type GetSemestersSemesterIdDisciplines200 = {
  disciplines: GetSemestersSemesterIdDisciplines200DisciplinesItem[]
}

export type GetSemestersSemesterIdDisciplines401 = {
  message: string
}

export type GetSemestersSemesterIdDisciplines404 = {
  message: string
}

export type GetDisciplinesDisciplineIdTasks200TasksItemDueDate = string | null

export type GetDisciplinesDisciplineIdTasks200TasksItemType =
  (typeof GetDisciplinesDisciplineIdTasks200TasksItemType)[keyof typeof GetDisciplinesDisciplineIdTasks200TasksItemType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetDisciplinesDisciplineIdTasks200TasksItemType = {
  exam: 'exam',
  activity: 'activity',
} as const

export type GetDisciplinesDisciplineIdTasks200TasksItemCreatedAt = string | null

export type GetDisciplinesDisciplineIdTasks200TasksItemUpdatedAt = string | null

export type GetDisciplinesDisciplineIdTasks200TasksItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$ */
  id: string
  title: string
  description: string
  dueDate: GetDisciplinesDisciplineIdTasks200TasksItemDueDate
  type: GetDisciplinesDisciplineIdTasks200TasksItemType
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$ */
  disciplineId: string
  createdAt: GetDisciplinesDisciplineIdTasks200TasksItemCreatedAt
  updatedAt: GetDisciplinesDisciplineIdTasks200TasksItemUpdatedAt
}

export type GetDisciplinesDisciplineIdTasks200 = {
  tasks: GetDisciplinesDisciplineIdTasks200TasksItem[]
}

export type GetDisciplinesDisciplineIdTasks401 = {
  message: string
}

export type GetDisciplinesDisciplineIdTasks404 = {
  message: string
}

export type PostTasksBodyType =
  (typeof PostTasksBodyType)[keyof typeof PostTasksBodyType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostTasksBodyType = {
  exam: 'exam',
  activity: 'activity',
} as const

export type PostTasksBody = {
  /** @minLength 3 */
  title: string
  /** @minLength 5 */
  description: string
  dueDate: unknown
  type: PostTasksBodyType
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$ */
  disciplineId: string
}

export type PostTasks201TaskDueDate = string | null

export type PostTasks201TaskType =
  (typeof PostTasks201TaskType)[keyof typeof PostTasks201TaskType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostTasks201TaskType = {
  exam: 'exam',
  activity: 'activity',
} as const

export type PostTasks201TaskCreatedAt = string | null

export type PostTasks201TaskUpdatedAt = string | null

export type PostTasks201Task = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$ */
  id: string
  title: string
  description: string
  dueDate: PostTasks201TaskDueDate
  type: PostTasks201TaskType
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$ */
  disciplineId: string
  createdAt: PostTasks201TaskCreatedAt
  updatedAt: PostTasks201TaskUpdatedAt
}

export type PostTasks201 = {
  task: PostTasks201Task
}

export type PostTasks400 = {
  message: string
}

export type PostTasks401 = {
  message: string
}

export type DeleteTasksTaskId200 = {
  success: boolean
}

export type DeleteTasksTaskId404Message = string | null

export type DeleteTasksTaskId404 = {
  message?: DeleteTasksTaskId404Message
}

export type PatchTasksTaskIdBodyType =
  (typeof PatchTasksTaskIdBodyType)[keyof typeof PatchTasksTaskIdBodyType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PatchTasksTaskIdBodyType = {
  exam: 'exam',
  activity: 'activity',
} as const

export type PatchTasksTaskIdBody = {
  /** @minLength 1 */
  title?: string
  /** @minLength 1 */
  description?: string
  dueDate?: unknown
  type?: PatchTasksTaskIdBodyType
}

export type PatchTasksTaskId200 = {
  success: boolean
}

export type PatchTasksTaskId404Message = string | null

export type PatchTasksTaskId404 = {
  message?: PatchTasksTaskId404Message
}

/**
 * @summary Sign up on the platform
 */
export const getPostSignupUrl = () => {
  return `http://localhost:3333/signup`
}

export const postSignup = async (
  postSignupBody: PostSignupBody,
  options?: RequestInit
): Promise<PostSignup201> => {
  const res = await fetch(getPostSignupUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postSignupBody),
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: PostSignup201 = body ? JSON.parse(body) : {}

  return data
}

/**
 * @summary Sign in on the platform
 */
export const getPostSigninUrl = () => {
  return `http://localhost:3333/signin`
}

export const postSignin = async (
  postSigninBody: PostSigninBody,
  options?: RequestInit
): Promise<PostSignin200> => {
  const res = await fetch(getPostSigninUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postSigninBody),
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: PostSignin200 = body ? JSON.parse(body) : {}

  return data
}

/**
 * @summary Course creation on the platform
 */
export const getPostCoursesUrl = () => {
  return `http://localhost:3333/courses`
}

export const postCourses = async (
  postCoursesBody: PostCoursesBody,
  options?: RequestInit
): Promise<PostCourses201> => {
  const res = await fetch(getPostCoursesUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postCoursesBody),
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: PostCourses201 = body ? JSON.parse(body) : {}

  return data
}

/**
 * @summary Get courses from authenticated user
 */
export const getGetCoursesUrl = () => {
  return `http://localhost:3333/courses`
}

export const getCourses = async (
  options?: RequestInit
): Promise<GetCourses200> => {
  const res = await fetch(getGetCoursesUrl(), {
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: GetCourses200 = body ? JSON.parse(body) : {}

  return data
}

/**
 * @summary Semester creation on the platform
 */
export const getPostSemestersUrl = () => {
  return `http://localhost:3333/semesters`
}

export const postSemesters = async (
  postSemestersBody: PostSemestersBody,
  options?: RequestInit
): Promise<PostSemesters201> => {
  const res = await fetch(getPostSemestersUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postSemestersBody),
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: PostSemesters201 = body ? JSON.parse(body) : {}

  return data
}

/**
 * @summary Discipline creation on the platform
 */
export const getPostDisciplinesUrl = () => {
  return `http://localhost:3333/disciplines`
}

export const postDisciplines = async (
  postDisciplinesBody: PostDisciplinesBody,
  options?: RequestInit
): Promise<PostDisciplines201> => {
  const res = await fetch(getPostDisciplinesUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postDisciplinesBody),
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: PostDisciplines201 = body ? JSON.parse(body) : {}

  return data
}

/**
 * @summary Get semesters from authenticated user course
 */
export const getGetCoursesCourseIdSemestersUrl = (courseId: string) => {
  return `http://localhost:3333/courses/${courseId}/semesters`
}

export const getCoursesCourseIdSemesters = async (
  courseId: string,
  options?: RequestInit
): Promise<GetCoursesCourseIdSemesters200> => {
  const res = await fetch(getGetCoursesCourseIdSemestersUrl(courseId), {
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: GetCoursesCourseIdSemesters200 = body ? JSON.parse(body) : {}

  return data
}

/**
 * @summary Get disciplines from a semester of authenticated user
 */
export const getGetSemestersSemesterIdDisciplinesUrl = (semesterId: string) => {
  return `http://localhost:3333/semesters/${semesterId}/disciplines`
}

export const getSemestersSemesterIdDisciplines = async (
  semesterId: string,
  options?: RequestInit
): Promise<GetSemestersSemesterIdDisciplines200> => {
  const res = await fetch(getGetSemestersSemesterIdDisciplinesUrl(semesterId), {
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: GetSemestersSemesterIdDisciplines200 = body
    ? JSON.parse(body)
    : {}

  return data
}

/**
 * @summary Get tasks of a discipline for authenticated user
 */
export const getGetDisciplinesDisciplineIdTasksUrl = (disciplineId: string) => {
  return `http://localhost:3333/disciplines/${disciplineId}/tasks`
}

export const getDisciplinesDisciplineIdTasks = async (
  disciplineId: string,
  options?: RequestInit
): Promise<GetDisciplinesDisciplineIdTasks200> => {
  const res = await fetch(getGetDisciplinesDisciplineIdTasksUrl(disciplineId), {
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: GetDisciplinesDisciplineIdTasks200 = body ? JSON.parse(body) : {}

  return data
}

/**
 * @summary Create task for a discipline
 */
export const getPostTasksUrl = () => {
  return `http://localhost:3333/tasks`
}

export const postTasks = async (
  postTasksBody: PostTasksBody,
  options?: RequestInit
): Promise<PostTasks201> => {
  const res = await fetch(getPostTasksUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postTasksBody),
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: PostTasks201 = body ? JSON.parse(body) : {}

  return data
}

/**
 * @summary Delete a task (owned by the authenticated user)
 */
export const getDeleteTasksTaskIdUrl = (taskId: string) => {
  return `http://localhost:3333/tasks/${taskId}`
}

export const deleteTasksTaskId = async (
  taskId: string,
  options?: RequestInit
): Promise<DeleteTasksTaskId200> => {
  const res = await fetch(getDeleteTasksTaskIdUrl(taskId), {
    ...options,
    method: 'DELETE',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: DeleteTasksTaskId200 = body ? JSON.parse(body) : {}

  return data
}

/**
 * @summary Update a task (owned by the authenticated user)
 */
export const getPatchTasksTaskIdUrl = (taskId: string) => {
  return `http://localhost:3333/tasks/${taskId}`
}

export const patchTasksTaskId = async (
  taskId: string,
  patchTasksTaskIdBody: PatchTasksTaskIdBody,
  options?: RequestInit
): Promise<PatchTasksTaskId200> => {
  const res = await fetch(getPatchTasksTaskIdUrl(taskId), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(patchTasksTaskIdBody),
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: PatchTasksTaskId200 = body ? JSON.parse(body) : {}

  return data
}
